<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Recipe Recommendations</title>
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <style>
        body {
            font-family: 'Roboto', sans-serif;
            background: #f7f7f7;
            color: #333;
            margin: 0;
            padding: 20px;
        }
        .container {
            background: white;
            border-radius: 8px;
            box-shadow: 0 2px 5px rgba(0,0,0,0.1);
            margin: 20px auto;
            padding: 20px;
            max-width: 800px;
        }
        .recipe-info {
            cursor: pointer;
            border-bottom: 2px solid #eee;
            padding: 10px 5px;
            transition: background-color 0.3s;
        }
        .recipe-info:hover {
            background-color: #f9f9f9;
        }
        .recipe-details {
            display: none;
            margin-top: 10px;
            padding: 10px;
            background-color: #fafafa;
            border-left: 3px solid #009688;
        }
        .recipe-details img {
            max-width: 100%;
            height: auto;
            border-radius: 4px;
        }
    </style>
</head>
<body>
    <div class="container">
        <?php
        $user_query = $_POST['query'];
        $user_prep_time = intval($_POST['prep_time']);
        $user_num_people = intval($_POST['num_people']);

        // Call the Python script
        $command = escapeshellcmd("python ML_rcmnd.py \"$user_query\" $user_prep_time $user_num_people");
        $html_output = shell_exec($command);

        // Display the HTML content generated by the Python script
        echo $html_output;
        ?>
    </div>

    <script src="js/jquery.min.js"></script>
    <script>
        // Function to toggle recipe details visibility
        $(document).ready(function(){
            $('.recipe-info').click(function(){
                $(this).next('.recipe-details').slideToggle();
            });
        });
    </script>
</body>
</html>
